version: "1.1"
pipeline:
  name: bodywork-serve-model-project
  docker_image: bodyworkml/bodywork-core:latest
  DAG: scoring_service
stages:
  scoring_service:
    executable_module_path: scoring_service/service.py
    requirements:
      - flask==2.1.2
      - joblib==1.1.0
      - numpy==1.22.3
      - scikit-learn==1.0.2
    cpu_request: 0.5
    memory_request_mb: 100
    service:
      max_startup_time_seconds: 120
      replicas: 2
      port: 5000
      ingress: true
logging:
  log_level: INFO
